# This script defines a GitHub Actions workflow that is triggered when a pull request is made to the `dev` branch, or when manually dispatched.        

name: APIHeartRate testing workflow # Workflow name
run-name: Run by @${{ github.actor }}  # Workflow runner
on:  
  workflow_dispatch: # Trigger the workflow when it is manually dispatched  
  pull_request: # Trigger the workflow when a pull request is made  
    branches: [ "dev" ] # Only trigger the workflow when the pull request is made to the `dev` branch    
jobs:  
  testing_job: # Define a job named `testing_job`  
    runs-on: macos-latest # Run the job on the `macos-latest` operating system  
    steps:  
    - uses: actions/checkout@v4 # Use the `actions/checkout` action to check out the repository's code  
    - uses: actions/cache@v3 # Use the `actions/cache` action to cache the Pods directory  
      with:  
        path: Pods  
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}  
        restore-keys: |  
          ${{ runner.os }}-pods-  
    - name: CocoaPods Install # Install CocoaPods dependencies  
      run: | # cd APIHeartRate # Position yourself inside the file that contains your podfile  
        pod install  
    - name: Test # Run tests for the BBL project  
      run: |  #   cd APIHeartRate  # Position yourself inside the file that contains your YourProjectName.xcworkspace file
        xcodebuild -workspace APIHeartRate.xcworkspace -scheme BBL -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test  
